export const CONGESTION_THRESHOLD_LOW = 0.8;
export const CONGESTION_THRESHOLD_MEDIUM = 0.5;
export const CONGESTION_ZOOM_LEVEL_THRESHOLD = 15;
export const CONGESTION_REFRESH_INTERVAL = 30000;
export const CONGESTION_SHAPE_WEIGHT_DEFAULT = 4;
export const CONGESTION_SHAPE_WEIGHT_BOLD = 6;
