/** @jest-environment jsdom */
import React from 'react';
import '@testing-library/jest-dom';
import { render, screen, fireEvent } from '@testing-library/react';
import CreateDiversionWithoutMergeModal from './CreateDiversionWithoutMergeModal';

describe('<CreateDiversionWithoutMergeModal />', () => {
    let onConfirmation;
    let onCancel;

    beforeEach(() => {
        onConfirmation = jest.fn();
        onCancel = jest.fn();

        render(
            <CreateDiversionWithoutMergeModal
                onConfirmation={ onConfirmation }
                onCancel={ onCancel }
            />,
        );
    });

    it('renders the description and buttons', () => {
        expect(
            screen.getByText('TomTom autogenerated diversion shape is not applied to the route shape(s). Are you sure you want to proceed?'),
        ).toBeInTheDocument();
        expect(screen.getByText('Cancel')).toBeInTheDocument();
        expect(screen.getByText('Confirm')).toBeInTheDocument();
    });

    it('calls onCancel when Cancel button is clicked', () => {
        const cancelButton = screen.getByText('Cancel');
        fireEvent.click(cancelButton);
        expect(onCancel).toHaveBeenCalled();
    });

    it('calls onConfirmation when Confirm button is clicked', () => {
        const confirmButton = screen.getByText('Confirm');
        fireEvent.click(confirmButton);
        expect(onConfirmation).toHaveBeenCalled();
    });
});
